[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
russian_roulette = "DTHCPBTw6tFZDwbiSzKXXK8wQ7n7v5zJAH3Ex3uvoSK5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "test_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"
