[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
example_client = "EioKxQafFaRbM5Yo1NXp1SP9HaFaqWWErZYpcb1a5eAC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "test_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true

[test.validator]
url = "https://api.devnet.solana.com"
[[test.validator.clone]]
address = "VRFCBePmGTpZ234BhbzNNzmyg39Rgdd6VgdfhHwKypU"
